"""empty message

Revision ID: 23628ae692f1
Revises: 
Create Date: 2024-09-22 00:34:07.434870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23628ae692f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
